services:

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: Challenge2026
      ORACLE_DATABASE: CLYVOVET
    ports:

  "1521:1521"
volumes:
  oracle-data:/opt/oracle/oradata

api:
  build: .
  container_name: challenge-clyvo-api
  environment:
    SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
    SPRING_DATASOURCE_USERNAME: system
    SPRING_DATASOURCE_PASSWORD: Challenge2026
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
    SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
    SPRING_JPA_SHOW_SQL: "true"
    SERVER_PORT: "8080"
  ports:

  "8080:8080"
depends_on:
  oracle
restart: unless-stopped

volumes:
  oracle-data: