services:
    api:
      build: .
      container_name: challenge-clyvo-api
      environment:
        SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
        SPRING_DATASOURCE_USERNAME: rm563736 #Credenciais fornecidas pela FIAP
        SPRING_DATASOURCE_PASSWORD: 140607   #Credenciais fornecidas pela FIAP
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
        SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ports:
        - "8080:8080"
      depends_on:
        oracle:
          condition: service_healthy
      restart: unless-stopped